'use client'
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import NavbarComponent from "@/components/NavbarComponent";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import Navbar from "@/components/NavbarComponent";
import Footer from "@/components/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "MY NEXT APP",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {



  const router = useRouter()
  const login = () => {
    // if(req.pathUrl = "/login"){
    //   toast.warn("you@!!!!!!!!!!!!!!!")
    // }
    router.push('/login')
  }
  const logout = async () => {
    try {
      const response = await fetch("/api/users/logout", {
        method: 'POST', // Make sure you're using POST for logout
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        // Redirect to login page after successful logout
        toast.success('Logout Successfully');
        router.push('/login')
      } else {
        const data = await response.json();
        console.log(data);
        toast.error(data.message || "Logout Failed");
      }
    } catch (error) {
      console.error("Error during logout:", error);
      toast.error("An error occurred during logout");
    }
  };

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Navbar />
        {/* nav bar started here */}
        {children}
        <ToastContainer />

        {/* Footer Component */}
        <Footer />
      </body>
    </html>
  );
}
